language: node_js
notifications:
  email: false
node_js:
- '8.11'
script:
- yarn run build
deploy:
  provider: npm
  on:
    tags: true
  skip_cleanup: true
  email: lostintime.dev@gmail.com
  api_key:
    secure: SiuXmlFZEAbI1vgjhH/BpSZX5odJYaHmNmuM/UnUKZMeqBByGtz6eQY4KDDGk1A48CQmTpzQ6XAbWh8tSj2AhP+VPTcopTb18RRUJhfMXcZ/WwcD9yqWBiI7F7VLpm6sAIUDhJMeZvthnYqrdKIqc/t+zZmT0hCUCnk51uzH12jse93Mf9Ad62dsfYH9ge8UMFHn+NPMRqFMq3UwXSKEm4CiD12gfyGtX0uD+vYeFrlUxTMXwDtlgl9D5sH2CzvAkrEjirrLSMrn0+peVDs/5/sTV4M+DUdH7aOCcmjm4oELQEkG74+SjamWgPSjBQPo5vnsSn+YDji87QFi1I5t3slMruubW/q+JRGckj8eVaGxTSN3Mzcp+VtiYHkyTJ58QanRxu+FRXynrx39JE0hUGajjH0F0CXZSjdmqznWWiT2bFO5aLXOOOPTkUBLdg+AR1UqaLwU04XeL08csrttuSG4fVf+zX80NGx6sf42S1dglh7FsB3OTlk81uimthJ44QeRxvx4pVSkwG4WDk8mke/CrodGvGU/CrlCHrW3vS1OPARi8G0IDDh4hAvqOyVXraEeajPbstwo/6AvHG68N0AD91Y4Uy4fEv1ekR+gOs5m46Zk/nNDr2XbG4qQ4uvB0i1CW+/ter3qD7sfQkV6UuLivrd3sTRcHsYjgwkrzWk=
